import type { Metadata } from 'next'
import { Geist, Inter } from 'next/font/google'
import { Toaster } from 'sonner' // Import Toaster

import './globals.css'
import { Providers } from './providers'
import { ThemeProvider } from './theme-provider'

const geist = Geist({
	subsets: ['latin']
})

const inter = Inter({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700', '800'],
  variable: '--font-sans',
  display: 'swap'
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='ru' suppressHydrationWarning>
			<body className={`${geist.className} ${inter.variable} antialiased`}>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					<Providers>{children}</Providers>
					<Toaster richColors position="top-center" /> {/* Add Toaster component */}
				</ThemeProvider>
			</body>
		</html>
	)
}
