import type { Metadata } from 'next'
import { Geist, Inter } from 'next/font/google'

import './globals.css'
import { Providers } from './providers'

const geist = Geist({
	subsets: ['latin']
})

const inter = Inter({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700', '800'],
  variable: '--font-sans',
  display: 'swap'
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='ru'>
			<body className={`${geist.className} ${inter.variable} antialiased`}>
				<Providers>{children}</Providers>
			</body>
		</html>
	)
}
