/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Education platform
 * OpenAPI spec version: 0.0.1
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  AnalyticsControllerGetPopularLessons200Item,
  AnalyticsControllerGetSuccessRate200,
  AnalyticsControllerGetTimeSpent200,
  AnalyticsDto,
  AuthResponse,
  Certificate,
  ChangePasswordDto,
  CompleteSubjectDto,
  CreateCertificateDto,
  CreateLessonDto,
  CreateProgressDto,
  CreateQuizDto,
  CreateSubjectDto,
  CreateTopicDto,
  CreateUserDto,
  FilesControllerUploadFile200,
  FilesControllerUploadFileBody,
  GetMeDto,
  LearningPathDto,
  Lesson,
  LessonDescriptionDto,
  LoginRequest,
  NotificationDto,
  PrerequisitesDto,
  Progress,
  Quiz,
  RecommendationsDto,
  RegisterRequest,
  Subject,
  SubmitQuizDto,
  Topic,
  UpdateLessonDto,
  UpdateProgressDto,
  UpdateQuizDto,
  UpdateSubjectDto,
  UpdateTopicDto,
  UpdateUserDto,
  User
} from './types';

export const appControllerGetHello = <TData = AxiosResponse<void>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/`,options
    );
  }

/**
 * Creates a new user account and returns an access token in the response
 * @summary Register a new user
 */
export const authControllerRegister = <TData = AxiosResponse<AuthResponse>>(
    registerRequest: RegisterRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/auth/register`,
      registerRequest,options
    );
  }

/**
 * Authenticates a user and returns an access token in the response
 * @summary Login an existing user
 */
export const authControllerLogin = <TData = AxiosResponse<AuthResponse>>(
    loginRequest: LoginRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/auth/login`,
      loginRequest,options
    );
  }

/**
 * Generates a new access token based on the provided refresh token from cookies
 * @summary Refresh access token
 */
export const authControllerRefresh = <TData = AxiosResponse<AuthResponse>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/auth/refresh`,undefined,options
    );
  }

/**
 * Clears authentication cookies
 * @summary Logout user
 */
export const authControllerLogout = <TData = AxiosResponse<void>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/auth/logout`,undefined,options
    );
  }

/**
 * @summary Создать нового пользователя (только для админов)
 */
export const usersControllerCreate = <TData = AxiosResponse<User>>(
    createUserDto: CreateUserDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/users`,
      createUserDto,options
    );
  }

/**
 * @summary Получить всех пользователей (только для админов)
 */
export const usersControllerGetAllUsers = <TData = AxiosResponse<User[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/users`,options
    );
  }

/**
 * @summary Обновить пользователя по ID (только для админов)
 */
export const usersControllerUpdate = <TData = AxiosResponse<User>>(
    id: string,
    updateUserDto: UpdateUserDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `/users/${id}`,
      updateUserDto,options
    );
  }

/**
 * @summary Получить информацию о текущем пользователе
 */
export const usersControllerGetMe = <TData = AxiosResponse<GetMeDto>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/users/@me`,options
    );
  }

/**
 * @summary Обновить информацию о текущем пользователе
 */
export const usersControllerUpdateMe = <TData = AxiosResponse<User>>(
    updateUserDto: UpdateUserDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `/users/@me`,
      updateUserDto,options
    );
  }

/**
 * @summary Изменить пароль текущего пользователя
 */
export const usersControllerChangePassword = <TData = AxiosResponse<void>>(
    changePasswordDto: ChangePasswordDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `/users/@me/password`,
      changePasswordDto,options
    );
  }

/**
 * @summary Создать новый предмет (курс) (только для админов/модераторов)
 */
export const subjectsControllerCreate = <TData = AxiosResponse<Subject>>(
    createSubjectDto: CreateSubjectDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/subjects`,
      createSubjectDto,options
    );
  }

/**
 * @summary Получить все предметы (курсы)
 */
export const subjectsControllerFindAll = <TData = AxiosResponse<Subject[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/subjects`,options
    );
  }

/**
 * @summary Найти предмет (курс) по ID
 */
export const subjectsControllerFindOne = <TData = AxiosResponse<Subject>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/subjects/${id}`,options
    );
  }

/**
 * @summary Обновить предмет (курс) (только для админов/модераторов)
 */
export const subjectsControllerUpdate = <TData = AxiosResponse<Subject>>(
    id: string,
    updateSubjectDto: UpdateSubjectDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `/subjects/${id}`,
      updateSubjectDto,options
    );
  }

/**
 * @summary Удалить предмет (курс) (только для админов/модераторов)
 */
export const subjectsControllerRemove = <TData = AxiosResponse<void>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/subjects/${id}`,options
    );
  }

/**
 * @summary Получить полный путь обучения по курсу с зависимостями
 */
export const subjectsControllerGetLearningPath = <TData = AxiosResponse<LearningPathDto>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/subjects/${id}/learning-path`,options
    );
  }

/**
 * @summary Получить полный путь обучения по курсу с зависимостями
 */
export const learningPathControllerGetLearningPath = <TData = AxiosResponse<LearningPathDto>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/learning-path/subjects/${id}`,options
    );
  }

/**
 * @summary Создать новую тему (только для админов/модераторов)
 */
export const topicsControllerCreate = <TData = AxiosResponse<Topic>>(
    createTopicDto: CreateTopicDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/topics`,
      createTopicDto,options
    );
  }

/**
 * @summary Получить все темы
 */
export const topicsControllerFindAll = <TData = AxiosResponse<Topic[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/topics`,options
    );
  }

/**
 * @summary Найти тему по ID
 */
export const topicsControllerFindOne = <TData = AxiosResponse<Topic>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/topics/${id}`,options
    );
  }

/**
 * @summary Обновить тему (только для админов/модераторов)
 */
export const topicsControllerUpdate = <TData = AxiosResponse<Topic>>(
    id: string,
    updateTopicDto: UpdateTopicDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `/topics/${id}`,
      updateTopicDto,options
    );
  }

/**
 * @summary Удалить тему (только для админов/модераторов)
 */
export const topicsControllerRemove = <TData = AxiosResponse<void>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/topics/${id}`,options
    );
  }

/**
 * @summary Создать новый урок
 */
export const lessonsControllerCreate = <TData = AxiosResponse<Lesson>>(
    createLessonDto: CreateLessonDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/lessons`,
      createLessonDto,options
    );
  }

/**
 * @summary Получить все уроки
 */
export const lessonsControllerFindAll = <TData = AxiosResponse<Lesson[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/lessons`,options
    );
  }

/**
 * @summary Найти урок по ID
 */
export const lessonsControllerFindOne = <TData = AxiosResponse<Lesson>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/lessons/${id}`,options
    );
  }

/**
 * @summary Обновить урок
 */
export const lessonsControllerUpdate = <TData = AxiosResponse<Lesson>>(
    id: string,
    updateLessonDto: UpdateLessonDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `/lessons/${id}`,
      updateLessonDto,options
    );
  }

/**
 * @summary Удалить урок
 */
export const lessonsControllerRemove = <TData = AxiosResponse<void>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/lessons/${id}`,options
    );
  }

/**
 * @summary Получить детальное описание урока с целями обучения и требованиями
 */
export const lessonsControllerGetLessonDescription = <TData = AxiosResponse<LessonDescriptionDto>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/lessons/${id}/description`,options
    );
  }

/**
 * @summary Получить список уроков, которые нужно пройти перед текущим
 */
export const lessonsControllerGetLessonPrerequisites = <TData = AxiosResponse<PrerequisitesDto>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/lessons/${id}/prerequisites`,options
    );
  }

/**
 * @summary Создать новый тест (только для админов/модераторов)
 */
export const quizzesControllerCreate = <TData = AxiosResponse<Quiz>>(
    createQuizDto: CreateQuizDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/quizzes`,
      createQuizDto,options
    );
  }

/**
 * @summary Получить все тесты
 */
export const quizzesControllerFindAll = <TData = AxiosResponse<Quiz[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/quizzes`,options
    );
  }

/**
 * @summary Найти тест по ID
 */
export const quizzesControllerFindOne = <TData = AxiosResponse<Quiz>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/quizzes/${id}`,options
    );
  }

/**
 * @summary Обновить тест (только для админов/модераторов)
 */
export const quizzesControllerUpdate = <TData = AxiosResponse<Quiz>>(
    id: string,
    updateQuizDto: UpdateQuizDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `/quizzes/${id}`,
      updateQuizDto,options
    );
  }

/**
 * @summary Удалить тест (только для админов/модераторов)
 */
export const quizzesControllerRemove = <TData = AxiosResponse<void>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/quizzes/${id}`,options
    );
  }

/**
 * @summary Найти тест по ID урока
 */
export const quizzesControllerFindByLessonId = <TData = AxiosResponse<Quiz>>(
    lessonId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/quizzes/lesson/${lessonId}`,options
    );
  }

/**
 * @summary Отправить ответы на тест
 */
export const quizzesControllerSubmit = <TData = AxiosResponse<void>>(
    id: string,
    submitQuizDto: SubmitQuizDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/quizzes/${id}/submit`,
      submitQuizDto,options
    );
  }

/**
 * @summary Создать запись о прогрессе (только для админов/модераторов)
 */
export const progressControllerCreate = <TData = AxiosResponse<Progress>>(
    createProgressDto: CreateProgressDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/progress`,
      createProgressDto,options
    );
  }

/**
 * @summary Получить весь прогресс для текущего пользователя
 */
export const progressControllerFindAll = <TData = AxiosResponse<Progress[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/progress`,options
    );
  }

/**
 * @summary Получить прогресс по конкретному уроку для текущего пользователя
 */
export const progressControllerFindOne = <TData = AxiosResponse<Progress>>(
    lessonId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/progress/${lessonId}`,options
    );
  }

/**
 * @summary Обновить прогресс по уроку (только для админов/модераторов)
 */
export const progressControllerUpdate = <TData = AxiosResponse<Progress>>(
    lessonId: string,
    updateProgressDto: UpdateProgressDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `/progress/${lessonId}`,
      updateProgressDto,options
    );
  }

/**
 * @summary Удалить прогресс по уроку (только для админов/модераторов)
 */
export const progressControllerRemove = <TData = AxiosResponse<void>>(
    lessonId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/progress/${lessonId}`,options
    );
  }

/**
 * @summary Завершить все уроки по предмету (только для админов/модераторов)
 */
export const progressControllerCompleteSubject = <TData = AxiosResponse<void>>(
    completeSubjectDto: CompleteSubjectDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/progress/complete-subject`,
      completeSubjectDto,options
    );
  }

/**
 * @summary Создать новое уведомление
 */
export const notificationsControllerCreateNotification = <TData = AxiosResponse<NotificationDto>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/notifications`,undefined,options
    );
  }

/**
 * @summary Создать уведомление с рекомендацией
 */
export const notificationsControllerCreateRecommendationNotification = <TData = AxiosResponse<NotificationDto>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/notifications/recommendation`,undefined,options
    );
  }

/**
 * @summary Получить все уведомления для пользователя
 */
export const notificationsControllerGetUserNotifications = <TData = AxiosResponse<NotificationDto[]>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/notifications/users/${id}`,options
    );
  }

/**
 * @summary Получить уведомления для текущего авторизованного пользователя
 */
export const notificationsControllerGetCurrentUserNotifications = <TData = AxiosResponse<NotificationDto[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/notifications/current-user`,options
    );
  }

/**
 * @summary Отметить уведомление как прочитанное
 */
export const notificationsControllerMarkAsRead = <TData = AxiosResponse<NotificationDto>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/notifications/${id}/read`,undefined,options
    );
  }

/**
 * @summary Удалить уведомление
 */
export const notificationsControllerDeleteNotification = <TData = AxiosResponse<void>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/notifications/${id}`,options
    );
  }

/**
 * @summary Создать новый сертификат
 */
export const certificatesControllerCreate = <TData = AxiosResponse<Certificate>>(
    createCertificateDto: CreateCertificateDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/certificates`,
      createCertificateDto,options
    );
  }

/**
 * @summary Получить все сертификаты (только для админов)
 */
export const certificatesControllerFindAll = <TData = AxiosResponse<Certificate[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/certificates`,options
    );
  }

/**
 * @summary Найти сертификаты по ID пользователя
 */
export const certificatesControllerFindByUser = <TData = AxiosResponse<Certificate[]>>(
    userId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/certificates/user/${userId}`,options
    );
  }

/**
 * @summary Найти сертификат по ID
 */
export const certificatesControllerFindOne = <TData = AxiosResponse<Certificate>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/certificates/${id}`,options
    );
  }

/**
 * @summary Скачать сертификат в формате PDF
 */
export const certificatesControllerDownload = <TData = AxiosResponse<Blob>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/certificates/${id}/download`,{
        responseType: 'blob',
    ...options,}
    );
  }

/**
 * @summary Загрузить файл
 */
export const filesControllerUploadFile = <TData = AxiosResponse<FilesControllerUploadFile200>>(
    filesControllerUploadFileBody: FilesControllerUploadFileBody, options?: AxiosRequestConfig
 ): Promise<TData> => {const formData = new FormData();
if(filesControllerUploadFileBody.file !== undefined) {
 formData.append(`file`, filesControllerUploadFileBody.file)
 }

    return axios.post(
      `/files/upload`,
      formData,options
    );
  }

/**
 * @summary Получить рекомендации следующих уроков на основе прогресса пользователя
 */
export const recommendationsControllerGetRecommendationsForUser = <TData = AxiosResponse<RecommendationsDto>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/recommendations/users/${id}`,options
    );
  }

/**
 * @summary Получить рекомендации для текущего авторизованного пользователя
 */
export const recommendationsControllerGetRecommendationsForCurrentUser = <TData = AxiosResponse<RecommendationsDto>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/recommendations/current-user`,options
    );
  }

/**
 * @summary Получить статистику обучения: время, прогресс, сильные/слабые стороны
 */
export const analyticsControllerGetUserAnalytics = <TData = AxiosResponse<AnalyticsDto>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/analytics/users/${id}`,options
    );
  }

/**
 * @summary Получить аналитику для текущего авторизованного пользователя
 */
export const analyticsControllerGetCurrentUserAnalytics = <TData = AxiosResponse<AnalyticsDto>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/analytics/current-user`,options
    );
  }

/**
 * @summary Получить время, потраченное на обучение
 */
export const analyticsControllerGetTimeSpent = <TData = AxiosResponse<AnalyticsControllerGetTimeSpent200>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/analytics/user/${id}/time-spent`,options
    );
  }

/**
 * @summary Получить успешность прохождения тестов
 */
export const analyticsControllerGetSuccessRate = <TData = AxiosResponse<AnalyticsControllerGetSuccessRate200>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/analytics/user/${id}/success-rate`,options
    );
  }

/**
 * @summary Получить популярные уроки в курсе
 */
export const analyticsControllerGetPopularLessons = <TData = AxiosResponse<AnalyticsControllerGetPopularLessons200Item[]>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/analytics/course/${id}/popular-lessons`,options
    );
  }

export type AppControllerGetHelloResult = AxiosResponse<void>
export type AuthControllerRegisterResult = AxiosResponse<AuthResponse>
export type AuthControllerLoginResult = AxiosResponse<AuthResponse>
export type AuthControllerRefreshResult = AxiosResponse<AuthResponse>
export type AuthControllerLogoutResult = AxiosResponse<void>
export type UsersControllerCreateResult = AxiosResponse<User>
export type UsersControllerGetAllUsersResult = AxiosResponse<User[]>
export type UsersControllerUpdateResult = AxiosResponse<User>
export type UsersControllerGetMeResult = AxiosResponse<GetMeDto>
export type UsersControllerUpdateMeResult = AxiosResponse<User>
export type UsersControllerChangePasswordResult = AxiosResponse<void>
export type SubjectsControllerCreateResult = AxiosResponse<Subject>
export type SubjectsControllerFindAllResult = AxiosResponse<Subject[]>
export type SubjectsControllerFindOneResult = AxiosResponse<Subject>
export type SubjectsControllerUpdateResult = AxiosResponse<Subject>
export type SubjectsControllerRemoveResult = AxiosResponse<void>
export type SubjectsControllerGetLearningPathResult = AxiosResponse<LearningPathDto>
export type LearningPathControllerGetLearningPathResult = AxiosResponse<LearningPathDto>
export type TopicsControllerCreateResult = AxiosResponse<Topic>
export type TopicsControllerFindAllResult = AxiosResponse<Topic[]>
export type TopicsControllerFindOneResult = AxiosResponse<Topic>
export type TopicsControllerUpdateResult = AxiosResponse<Topic>
export type TopicsControllerRemoveResult = AxiosResponse<void>
export type LessonsControllerCreateResult = AxiosResponse<Lesson>
export type LessonsControllerFindAllResult = AxiosResponse<Lesson[]>
export type LessonsControllerFindOneResult = AxiosResponse<Lesson>
export type LessonsControllerUpdateResult = AxiosResponse<Lesson>
export type LessonsControllerRemoveResult = AxiosResponse<void>
export type LessonsControllerGetLessonDescriptionResult = AxiosResponse<LessonDescriptionDto>
export type LessonsControllerGetLessonPrerequisitesResult = AxiosResponse<PrerequisitesDto>
export type QuizzesControllerCreateResult = AxiosResponse<Quiz>
export type QuizzesControllerFindAllResult = AxiosResponse<Quiz[]>
export type QuizzesControllerFindOneResult = AxiosResponse<Quiz>
export type QuizzesControllerUpdateResult = AxiosResponse<Quiz>
export type QuizzesControllerRemoveResult = AxiosResponse<void>
export type QuizzesControllerFindByLessonIdResult = AxiosResponse<Quiz>
export type QuizzesControllerSubmitResult = AxiosResponse<void>
export type ProgressControllerCreateResult = AxiosResponse<Progress>
export type ProgressControllerFindAllResult = AxiosResponse<Progress[]>
export type ProgressControllerFindOneResult = AxiosResponse<Progress>
export type ProgressControllerUpdateResult = AxiosResponse<Progress>
export type ProgressControllerRemoveResult = AxiosResponse<void>
export type ProgressControllerCompleteSubjectResult = AxiosResponse<void>
export type NotificationsControllerCreateNotificationResult = AxiosResponse<NotificationDto>
export type NotificationsControllerCreateRecommendationNotificationResult = AxiosResponse<NotificationDto>
export type NotificationsControllerGetUserNotificationsResult = AxiosResponse<NotificationDto[]>
export type NotificationsControllerGetCurrentUserNotificationsResult = AxiosResponse<NotificationDto[]>
export type NotificationsControllerMarkAsReadResult = AxiosResponse<NotificationDto>
export type NotificationsControllerDeleteNotificationResult = AxiosResponse<void>
export type CertificatesControllerCreateResult = AxiosResponse<Certificate>
export type CertificatesControllerFindAllResult = AxiosResponse<Certificate[]>
export type CertificatesControllerFindByUserResult = AxiosResponse<Certificate[]>
export type CertificatesControllerFindOneResult = AxiosResponse<Certificate>
export type CertificatesControllerDownloadResult = AxiosResponse<Blob>
export type FilesControllerUploadFileResult = AxiosResponse<FilesControllerUploadFile200>
export type RecommendationsControllerGetRecommendationsForUserResult = AxiosResponse<RecommendationsDto>
export type RecommendationsControllerGetRecommendationsForCurrentUserResult = AxiosResponse<RecommendationsDto>
export type AnalyticsControllerGetUserAnalyticsResult = AxiosResponse<AnalyticsDto>
export type AnalyticsControllerGetCurrentUserAnalyticsResult = AxiosResponse<AnalyticsDto>
export type AnalyticsControllerGetTimeSpentResult = AxiosResponse<AnalyticsControllerGetTimeSpent200>
export type AnalyticsControllerGetSuccessRateResult = AxiosResponse<AnalyticsControllerGetSuccessRate200>
export type AnalyticsControllerGetPopularLessonsResult = AxiosResponse<AnalyticsControllerGetPopularLessons200Item[]>
