/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Education platform
 * OpenAPI spec version: 0.0.1
 */

export interface Answer {
  /** Уникальный идентификатор ответа */
  id: string;
  /** Текст ответа */
  text: string;
  /** Является ли ответ правильным */
  isCorrect: boolean;
  /** ID вопроса, к которому относится ответ */
  questionId: string;
  /** Дата создания записи */
  createdAt: string;
  /** Дата последнего обновления записи */
  updatedAt: string;
}
