/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Education platform
 * OpenAPI spec version: 0.0.1
 */

export interface AuthResponse {
  /** Access token used for authorization */
  accessToken: string;
  /** Refresh token used for refreshing access token */
  refreshToken: string;
}
