/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Education platform
 * OpenAPI spec version: 0.0.1
 */

export interface ChangePasswordDto {
  /** Текущий пароль пользователя */
  currentPassword: string;
  /** Новый пароль пользователя */
  newPassword: string;
}
