/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Education platform
 * OpenAPI spec version: 0.0.1
 */

export interface CourseAnalyticsDto {
  /** ID курса */
  courseId: string;
  /** Количество студентов на курсе */
  numberOfStudents: number;
  /** Средний процент завершения курса */
  averageCompletionRate: number;
  /** Средний балл по тестам в курсе */
  averageScore: number;
}
