/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Education platform
 * OpenAPI spec version: 0.0.1
 */

export interface CreateLessonDto {
  /** The title of the lesson */
  title: string;
  /** The content of the lesson in HTML format */
  content: string;
  /** The ID of the topic this lesson belongs to */
  topicId: string;
}
