/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Education platform
 * OpenAPI spec version: 0.0.1
 */
import type { CreateQuestionDto } from './createQuestionDto';

export interface CreateQuizDto {
  /** The title of the quiz */
  title: string;
  /** The ID of the lesson this quiz is for */
  lessonId: string;
  /** A list of questions for the quiz */
  questions: CreateQuestionDto[];
  /** Time limit for the quiz in minutes */
  timeLimit?: number;
  /** Maximum number of attempts allowed */
  maxAttempts?: number;
  /** Passing score in percentage */
  passingScore?: number;
  /** Whether to shuffle questions */
  shuffleQuestions?: boolean;
  /** Whether to shuffle answers */
  shuffleAnswers?: boolean;
}
