/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Education platform
 * OpenAPI spec version: 0.0.1
 */

export interface CreateCertificateDto {
  /** The ID of the user */
  userId: string;
  /** The ID of the subject */
  subjectId: string;
}
