/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Education platform
 * OpenAPI spec version: 0.0.1
 */
import type { CreateQuestionDtoType } from './createQuestionDtoType';
import type { CreateAnswerDto } from './createAnswerDto';

export interface CreateQuestionDto {
  /** The text of the question */
  text: string;
  /** The type of the question */
  type: CreateQuestionDtoType;
  /** A list of possible answers for the question */
  answers: CreateAnswerDto[];
}
