/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Education platform
 * OpenAPI spec version: 0.0.1
 */

export interface CreateTopicDto {
  /** The title of the topic */
  title: string;
  /** The ID of the subject this topic belongs to */
  subjectId: string;
  /** The ID of the parent topic, if this is a sub-topic */
  parentId?: string;
  /** List of URLs to attachments */
  attachments?: string[];
}
