/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Education platform
 * OpenAPI spec version: 0.0.1
 */

/**
 * The type of the question
 */
export type CreateQuestionDtoType = typeof CreateQuestionDtoType[keyof typeof CreateQuestionDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateQuestionDtoType = {
  SINGLE_CHOICE: 'SINGLE_CHOICE',
  MULTIPLE_CHOICE: 'MULTIPLE_CHOICE',
} as const;
