/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Education platform
 * OpenAPI spec version: 0.0.1
 */
import type { PopularCourseDto } from './popularCourseDto';
import type { RecentActivityDto } from './recentActivityDto';

export interface DashboardDataDto {
  totalUsers: number;
  activeUsers: number;
  totalCourses: number;
  totalLessons: number;
  completionRate: number;
  averageTimeSpent: number;
  popularCourses: PopularCourseDto[];
  recentActivity: RecentActivityDto[];
}
