/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Education platform
 * OpenAPI spec version: 0.0.1
 */

/**
 * User role
 */
export type GetMeDtoRole = typeof GetMeDtoRole[keyof typeof GetMeDtoRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetMeDtoRole = {
  STUDENT: 'STUDENT',
  ADMIN: 'ADMIN',
  MODERATOR: 'MODERATOR',
} as const;
