/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Education platform
 * OpenAPI spec version: 0.0.1
 */
import type { GetMeDtoRole } from './getMeDtoRole';

export interface GetMeDto {
  /** User ID */
  id: string;
  /**
   * First name of the user
   * @nullable
   */
  firstName: string | null;
  /**
   * Last name of the user
   * @nullable
   */
  lastName: string | null;
  /** Email address of the user */
  email: string;
  /** User role */
  role: GetMeDtoRole;
  /**
   * Avatar URL
   * @nullable
   */
  avatarUrl: string | null;
  /** Whether the user receives notifications */
  receiveNotifications: boolean;
  /** Creation date */
  createdAt: string;
  /** Update date */
  updatedAt: string;
}
