/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Education platform
 * OpenAPI spec version: 0.0.1
 */
import type { GetMeDtoRole } from './getMeDtoRole';

export interface GetMeDto {
  /** User ID */
  id: string;
  /** Email address of the user */
  email: string;
  /** First name of the user */
  firstName: string;
  /** Last name of the user */
  lastName: string;
  /** User role */
  role: GetMeDtoRole;
}
