/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Education platform
 * OpenAPI spec version: 0.0.1
 */

export * from './authResponse';
export * from './completeSubjectDto';
export * from './createAnswerDto';
export * from './createCertificateDto';
export * from './createLessonDto';
export * from './createProgressDto';
export * from './createQuestionDto';
export * from './createQuestionDtoType';
export * from './createQuizDto';
export * from './createSubjectDto';
export * from './createTopicDto';
export * from './createUserDto';
export * from './createUserDtoRole';
export * from './getMeDto';
export * from './getMeDtoRole';
export * from './loginRequest';
export * from './registerRequest';
export * from './submitQuizDto';
export * from './updateAnswerDto';
export * from './updateLessonDto';
export * from './updateProgressDto';
export * from './updateQuestionDto';
export * from './updateQuestionDtoType';
export * from './updateQuizDto';
export * from './updateSubjectDto';
export * from './updateTopicDto';
export * from './updateUserDto';
export * from './updateUserDtoRole';
export * from './userAnswerDto';