/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Education platform
 * OpenAPI spec version: 0.0.1
 */

export type LearningPathDtoTopicsItemLessonsItem = {
  id?: string;
  title?: string;
  order?: number;
  estimatedTime?: number;
  difficulty?: number;
};
