/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Education platform
 * OpenAPI spec version: 0.0.1
 */
import type { LearningPathDtoTopicsItemLessonsItem } from './learningPathDtoTopicsItemLessonsItem';

export type LearningPathDtoTopicsItem = {
  id?: string;
  title?: string;
  lessons?: LearningPathDtoTopicsItemLessonsItem[];
};
