/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Education platform
 * OpenAPI spec version: 0.0.1
 */
import type { LearningPathDtoTopicsItem } from './learningPathDtoTopicsItem';

export interface LearningPathDto {
  /** ID курса, для которого строится путь обучения */
  subjectId: string;
  /** Название курса */
  subjectTitle: string;
  /** Описание курса */
  subjectDescription?: string;
  /** Список тем в курсе с уроками */
  topics: LearningPathDtoTopicsItem[];
}
