/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Education platform
 * OpenAPI spec version: 0.0.1
 */

export interface Lesson {
  /** Уникальный идентификатор урока */
  id: string;
  /** Название урока */
  title: string;
  /** Содержание урока в формате HTML или Markdown */
  content: string;
  /** ID темы, к которой относится урок */
  topicId: string;
  /** Дата создания записи */
  createdAt: string;
  /** Дата последнего обновления записи */
  updatedAt: string;
}
