/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Education platform
 * OpenAPI spec version: 0.0.1
 */
import type { Lesson } from './lesson';

export interface LessonDescriptionDto {
  /** Основная информация об уроке */
  lesson: Lesson;
  /** Цели обучения для урока */
  learningObjectives?: string;
  /** Требования для прохождения урока */
  prerequisites?: string;
  /** Рекомендуемое время прохождения урока в минутах */
  estimatedTime?: number;
  /** Сложность урока от 1 до 5 */
  difficulty?: number;
  /** Список вложений (PDF, документы и т.д.) */
  attachments?: string[];
}
