/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Education platform
 * OpenAPI spec version: 0.0.1
 */

export interface MonthlyProgress {
  /** Месяц (например, "Янв", "Фев") */
  name: string;
  /** Прогресс в процентах */
  progress: number;
}
