/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Education platform
 * OpenAPI spec version: 0.0.1
 */
import type { NotificationDtoType } from './notificationDtoType';
import type { NotificationDtoData } from './notificationDtoData';

export interface NotificationDto {
  /** Уникальный идентификатор уведомления */
  id: string;
  /** ID пользователя, которому отправляется уведомление */
  userId: string;
  /** Тип уведомления */
  type: NotificationDtoType;
  /** Заголовок уведомления */
  title: string;
  /** Содержание уведомления */
  message: string;
  /**
   * Дополнительные данные уведомления
   * @nullable
   */
  data: NotificationDtoData;
  /** Статус прочтения уведомления */
  isRead: boolean;
  /** Дата создания уведомления */
  createdAt: string;
  /** Дата последнего обновления уведомления */
  updatedAt: string;
}
