/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Education platform
 * OpenAPI spec version: 0.0.1
 */

/**
 * Тип уведомления
 */
export type NotificationDtoType = typeof NotificationDtoType[keyof typeof NotificationDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NotificationDtoType = {
  'lesson-completed': 'lesson-completed',
  'quiz-result': 'quiz-result',
  recommendation: 'recommendation',
  'course-completed': 'course-completed',
  'deadline-reminder': 'deadline-reminder',
} as const;
