/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Education platform
 * OpenAPI spec version: 0.0.1
 */

/**
 * Дополнительные данные уведомления
 * @nullable
 */
export type NotificationDtoData = { [key: string]: unknown } | null;
