/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Education platform
 * OpenAPI spec version: 0.0.1
 */
import type { User } from './user';

export interface PaginatedUsersDto {
  /** Массив элементов */
  data: User[];
  /** Общее количество элементов */
  total: number;
}
