/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Education platform
 * OpenAPI spec version: 0.0.1
 */
import type { Topic } from './topic';

export interface PaginatedTopicsDto {
  /** Массив элементов */
  data: Topic[];
  /** Общее количество элементов */
  total: number;
}
