/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Education platform
 * OpenAPI spec version: 0.0.1
 */

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type PaginatedSubjectsDtoDataItem = any;
