/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Education platform
 * OpenAPI spec version: 0.0.1
 */
import type { PrerequisitesDtoRequiredLessonsItem } from './prerequisitesDtoRequiredLessonsItem';

export interface PrerequisitesDto {
  /** ID урока, для которого запрашиваются зависимости */
  lessonId: string;
  /** Список уроков, которые нужно пройти перед текущим */
  requiredLessons: PrerequisitesDtoRequiredLessonsItem[];
}
