/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Education platform
 * OpenAPI spec version: 0.0.1
 */

export interface Progress {
  /** Уникальный идентификатор прогресса */
  id: string;
  /** ID пользователя */
  userId: string;
  /** ID урока */
  lessonId: string;
  /** Завершен ли урок */
  isCompleted: boolean;
  /** Балл за тест (если есть) */
  score?: number;
  /** Время, потраченное на урок (в минутах) */
  timeSpent?: number;
  /** Дата завершения урока */
  completedAt?: string;
  /** Дата создания записи */
  createdAt: string;
  /** Дата последнего обновления записи */
  updatedAt: string;
}
