/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Education platform
 * OpenAPI spec version: 0.0.1
 */

export interface Progress {
  /** Уникальный идентификатор прогресса */
  id: string;
  /** ID пользователя */
  userId: string;
  /** ID урока */
  lessonId: string;
  /** Завершен ли урок */
  isCompleted: boolean;
  /** Дата завершения урока */
  completedAt?: string;
  /** Дата создания записи */
  createdAt: string;
  /** Дата последнего обновления записи */
 updatedAt: string;
}

export interface UserProgress {
  // Define the structure for user progress stats
 // This is a placeholder - the actual structure depends on what the backend returns
  totalSubjects: number;
 completedSubjects: number;
  totalLessons: number;
 completedLessons: number;
  // Add other fields as needed based on the actual API response
}
