/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Education platform
 * OpenAPI spec version: 0.0.1
 */
import type { Question } from './question';

export interface Quiz {
  /** Уникальный идентификатор теста */
  id: string;
  /** Название теста */
  title: string;
  /** ID урока, к которому относится тест */
  lessonId: string;
  /** Список вопросов в тесте */
  questions: Question[];
  /** Дата создания записи */
  createdAt: string;
  /** Дата последнего обновления записи */
  updatedAt: string;
}
