/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Education platform
 * OpenAPI spec version: 0.0.1
 */
import type { RecommendationsDtoRecommendationsItem } from './recommendationsDtoRecommendationsItem';

export interface RecommendationsDto {
  /** ID пользователя, для которого генерируются рекомендации */
  userId: string;
  /** Список рекомендованных уроков */
  recommendations: RecommendationsDtoRecommendationsItem[];
  /** Дата генерации рекомендаций */
  generatedAt: string;
}
