/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Education platform
 * OpenAPI spec version: 0.0.1
 */

/**
 * Статус курса
 */
export type SubjectStatus = typeof SubjectStatus[keyof typeof SubjectStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SubjectStatus = {
  DRAFT: 'DRAFT',
  PUBLISHED: 'PUBLISHED',
  ARCHIVED: 'ARCHIVED',
} as const;
