/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Education platform
 * OpenAPI spec version: 0.0.1
 */
import type { SubjectDescription } from './subjectDescription';
import type { SubjectStatus } from './subjectStatus';
import type { Topic } from './topic';

export interface Subject {
  /** Уникальный идентификатор предмета */
  id: string;
  /** Название предмета */
  title: string;
  /** Описание предмета */
  description?: SubjectDescription;
  /** Статус курса */
  status: SubjectStatus;
  /** Список тем в предмете */
  topics: Topic[];
  /** Дата создания записи */
  createdAt: string;
  /** Дата последнего обновления записи */
  updatedAt: string;
}
