/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Education platform
 * OpenAPI spec version: 0.0.1
 */
import type { UserAnswerDto } from './userAnswerDto';

export interface SubmitQuizDto {
  /** A list of user answers for the quiz */
  answers: UserAnswerDto[];
}
