/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Education platform
 * OpenAPI spec version: 0.0.1
 */

/**
 * ID родительской темы (для иерархии)
 */
export type TopicParentId = { [key: string]: unknown };
