/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Education platform
 * OpenAPI spec version: 0.0.1
 */

/**
 * The role of the user
 */
export type UpdateUserDtoRole = typeof UpdateUserDtoRole[keyof typeof UpdateUserDtoRole];


export const UpdateUserDtoRole = {
  STUDENT: 'STUDENT',
  ADMIN: 'ADMIN',
  MODERATOR: 'MODERATOR',
} as const;
