/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Education platform
 * OpenAPI spec version: 0.0.1
 */

export interface UpdateAnswerDto {
  /** The unique ID of the answer */
  id?: string;
  /** The text of the answer */
  text?: string;
  /** Whether this answer is the correct one */
  isCorrect?: boolean;
}
