/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Education platform
 * OpenAPI spec version: 0.0.1
 */
import type { UpdateQuestionDtoType } from './updateQuestionDtoType';
import type { UpdateAnswerDto } from './updateAnswerDto';

export interface UpdateQuestionDto {
  /** The unique ID of the question */
  id?: string;
  /** The text of the question */
  text?: string;
  /** The type of the question */
  type?: UpdateQuestionDtoType;
  /** A list of possible answers for the question */
  answers?: UpdateAnswerDto[];
}
