/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Education platform
 * OpenAPI spec version: 0.0.1
 */
import type { UpdateQuestionDto } from './updateQuestionDto';

export interface UpdateQuizDto {
  /** The title of the quiz */
  title?: string;
  /** A list of questions for the quiz */
  questions?: UpdateQuestionDto[];
}
