/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Education platform
 * OpenAPI spec version: 0.0.1
 */

/**
 * Статус курса
 * @nullable
 */
export type UpdateSubjectDtoStatus = typeof UpdateSubjectDtoStatus[keyof typeof UpdateSubjectDtoStatus] | null;


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateSubjectDtoStatus = {
  DRAFT: 'DRAFT',
  PUBLISHED: 'PUBLISHED',
  ARCHIVED: 'ARCHIVED',
} as const;
