/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Education platform
 * OpenAPI spec version: 0.0.1
 */

export interface UpdateUserDto {
  /** Email address of the user */
  email?: string;
  /** Password for the account */
  password?: string;
  /** First name of the user */
  firstName?: string;
  /** Last name of the user */
  lastName?: string;
}
