/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Education platform
 * OpenAPI spec version: 0.0.1
 */

export interface UpdateProgressDto {
  /** Whether the lesson is completed */
  isCompleted?: boolean;
  /** Score obtained in the quiz (if any) */
  score?: number;
  /** Time spent on the lesson in minutes */
  timeSpent?: number;
}
