/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Education platform
 * OpenAPI spec version: 0.0.1
 */

export interface UserAnswerDto {
  /** The ID of the question being answered */
  questionId: string;
  /** An array of answer IDs selected by the user */
  answerIds: string[];
}
