/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Education platform
 * OpenAPI spec version: 0.0.1
 */

/**
 * Роль пользователя
 */
export type UserRole = typeof UserRole[keyof typeof UserRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserRole = {
  STUDENT: 'STUDENT',
  ADMIN: 'ADMIN',
  MODERATOR: 'MODERATOR',
} as const;
