/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Education platform
 * OpenAPI spec version: 0.0.1
 */
import type { UserFirstName } from './userFirstName';
import type { UserLastName } from './userLastName';
import type { UserRole } from './userRole';
import type { UserAvatarUrl } from './userAvatarUrl';
import type { UserPhone } from './userPhone';
import type { UserDob } from './userDob';
import type { UserCity } from './userCity';

export interface User {
  /** Уникальный идентификатор пользователя */
  id: string;
  /** Имя пользователя */
  firstName?: UserFirstName;
  /** Фамилия пользователя */
  lastName?: UserLastName;
  /** Адрес электронной почты */
  email: string;
  /** Роль пользователя */
  role: UserRole;
  /** URL аватара */
  avatarUrl?: UserAvatarUrl;
  /** Номер телефона */
  phone?: UserPhone;
  /** Дата рождения */
  dob?: UserDob;
  /** Город */
  city?: UserCity;
  /** Дата создания записи */
  createdAt: string;
  /** Дата последнего обновления записи */
  updatedAt: string;
}
