/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Education platform
 * OpenAPI spec version: 0.0.1
 */
import type { MonthlyProgress } from './monthlyProgress';

export interface UserProgressOverTimeDto {
  /** ID пользователя */
  userId: string;
  /** Прогресс пользователя по месяцам */
  monthlyProgress: MonthlyProgress[];
}
