/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Education platform
 * OpenAPI spec version: 0.0.1
 */
import type { UserRole } from './userRole';

export interface User {
  /** Уникальный идентификатор пользователя */
  id: string;
  /** Имя пользователя */
  firstName?: string;
  /** Фамилия пользователя */
  lastName?: string;
  /** Адрес электронной почты */
  email: string;
  /** Роль пользователя */
  role: UserRole;
  /** URL аватара */
  avatarUrl?: string;
  /** Номер телефона */
  phone?: string;
  /** Дата рождения */
  dob?: string;
  /** Город */
  city?: string;
  /** Получает ли пользователь уведомления */
  receiveNotifications: boolean;
  /** Дата создания записи */
  createdAt: string;
  /** Дата последнего обновления записи */
  updatedAt: string;
}
